-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.trips (
  id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        character varying(40)    NOT NULL,
  starts_at   timestamp with time zone NOT NULL,
  trip_type   text                     NOT NULL,
  trip_status text                     DEFAULT 'planning'::text NOT NULL,
  image_url   text,
  invite_link text                     NOT NULL,
  owner_id    uuid                     DEFAULT auth.uid() NOT NULL,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  updated_at  timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.trips
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.trips
  ADD CONSTRAINT name_not_blank CHECK (name::text = TRIM(BOTH FROM name) AND length(name::text) > 0);

ALTER TABLE public.trips
  ADD CONSTRAINT trip_status_valid CHECK (trip_status = ANY (ARRAY['planning'::text, 'in-trip'::text, 'completed'::text]));

ALTER TABLE public.trips
  ADD CONSTRAINT trip_type_valid CHECK (trip_type = ANY (ARRAY['one-way'::text, 'round trip'::text]));

ALTER TABLE public.trips
  ADD CONSTRAINT trips_invite_link_key UNIQUE (invite_link);

ALTER TABLE public.trips
  ADD CONSTRAINT trips_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.trips
  ADD CONSTRAINT trips_pkey PRIMARY KEY (id);

GRANT DELETE, INSERT, SELECT, UPDATE ON public.trips TO authenticated;

CREATE TRIGGER trips_set_updated_at
  BEFORE UPDATE ON public.trips
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "owners delete their trips" ON public.trips
  FOR DELETE
  TO authenticated
  USING ((owner_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "owners read their trips" ON public.trips
  FOR SELECT
  TO authenticated
  USING ((owner_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "owners update their trips" ON public.trips
  FOR UPDATE
  TO authenticated
  USING ((owner_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((owner_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "users create trips" ON public.trips
  FOR INSERT
  TO authenticated
  WITH CHECK ((owner_id = ( SELECT auth.uid() AS uid)));
